language: node_js
node_js:
- '8'
- '10'
- '12'
cache: yarn
script: yarn ci
deploy:
  edge: true
  provider: npm
  email: igor@kamyshev.me
  api_key:
    secure: djROAIFB6Y/d4XWOhuNPjlPAvZ+s8Oc9LhJ7i+hDZW6cCvwVMexevPBXLIrwOC5MXahMxoJWOP4VLxHvjj5xnxUDmEpl1M8VGWi+XRtiSrjpKYlp/kGIhSY5pTQ3PZERpbKJgmk7JaOmVTA0nCOhNLLEw1ZXlH8IhvekgdUYHsuSBbYLvoQUPz+xeBQuObIQXOd6oKEWKAC03ASYTWXAbsaVEX0t/rkXlp9BzBRA57JQnwVGOHJekDyvcB7LE3ldKW60cWVspLMZXlBSkcMBew8xjT86jLOXTDCYEqKrgG7fVTqiaq/La1dvxZvilAWod//xyMvUk2MZ9g1L88sSuLZwHvMh30aZID538m3a9ycLv7gREwQ6Iol5WeBKsWiUwZ6+xwNgmZiam9wh9mUZzc5Z/6t901zrHnFSLMjjJwYzG79rfE31Q4bMMC+5mz5f0A0XQCETI3gm1ABi/SIoydzUpzJ7D9r/8/mwr3lAvgyHXoZ3YZfVivgbJFQHdPSxRinuvX6OUbqy0NUS1VhHAQLvEcF6KBRRZwDzkdRlWElyYsWn1Khm3lHcHlCyKR8RKONboeA7/6QBtA5KBW2v0Inqjk/wateUmbO83PduvR0VajOCyDISI7naQJ+oPN+82SK7/eLeH+TBWyHTFM+MYpqKobfnnkM+53ZGo03tfm0=
  on:
    tags: true
    repo: samokat-oss/lint-release
